name: Build
on:
  push:
    branches: master

jobs:
  build:
    name: Build
    strategy:
      matrix: 
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
      - name: Run Static Link
        shell: bash
        run: cargo clean && cargo run --example=version --features=src_build,static_link
      - name: Run Shared Link
        run: cargo clean && cargo run --example=version --features=src_build
      